name = "SolarPosition"
uuid = "5b9d1343-a731-5a90-8730-7bf8d89bf3eb"
version = "0.3.2"
authors = ["Stefan de Lange"]

[workspace]
projects = ["test", "docs", "benchmark", "examples"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
SolarPositionMakieExt = "Makie"
SolarPositionModelingToolkitExt = ["ModelingToolkit", "Symbolics"]
SolarPositionOhMyThreadsExt = "OhMyThreads"

[compat]
Aqua = "0.8"
Dates = "1"
DocStringExtensions = "0.8, 0.9"
Makie = "0.24"
ModelingToolkit = "11"
OhMyThreads = "0.8"
StructArrays = "0.7"
Symbolics = "6,7"
Tables = "1"
Test = "1"
TimeZones = "1.22.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
